package dev.archcontext.service;
import dev.archcontext.domain.Models.*;import dev.archcontext.storage.Database;import dev.archcontext.util.Json;import dev.archcontext.yaml.YamlMapper;import java.nio.file.*;import java.sql.*;import java.util.*;
class ContextLoaders { final Path root; final YamlMapper yaml=new YamlMapper(); ContextLoaders(Path root){this.root=root;} Connection c() throws SQLException { return new Database(root.resolve(".archcontext/archcontext.db")).connect(); }
 Solution solution(){ try(Connection c=c(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT id,name,description FROM solution LIMIT 1")){return r.next()?new Solution(r.getString(1),r.getString(2),r.getString(3)):null;}catch(Exception e){throw new IllegalStateException(e);} }
 List<Principle> principles(){List<Principle> l=new ArrayList<>(); try(Connection c=c(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT id,title,description FROM principles")){while(r.next())l.add(new Principle(r.getString(1),r.getString(2),r.getString(3)));}catch(Exception e){throw new IllegalStateException(e);} return l;}
 List<RepositoryDefinition> repositories(){List<RepositoryDefinition> l=new ArrayList<>(); try(Connection c=c(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT id,name,COALESCE(resolved_path,path),type,language,bounded_context,description FROM repositories")){while(r.next())l.add(new RepositoryDefinition(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)));}catch(Exception e){throw new IllegalStateException(e);} return l;}
 Optional<RepositoryDefinition> repository(String id){return repositories().stream().filter(r->r.id().equals(id)).findFirst();}
 List<Spec> specs(){List<Spec> l=new ArrayList<>(); try(Connection c=c(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT id,title,status,owner,problem,business_goal,affected_bounded_contexts,constraints_json,related_adrs_json,source_path FROM specs")){while(r.next()){ Path p=Path.of(r.getString(10)); if(Files.exists(p)){ var d=yaml.read(p); if(d.spec!=null){ l.add(d.spec); continue; } } l.add(new Spec(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),impacts("spec",r.getString(1)),Json.stringList(r.getString(7)),List.of(),List.of(),List.of(),Json.stringList(r.getString(8)),Json.stringList(r.getString(9)),r.getString(10)));}}catch(Exception e){throw new IllegalStateException(e);} return l;}
 Optional<Spec> spec(String id){return specs().stream().filter(s->s.id().equals(id)).findFirst();}
 List<Adr> adrs(){List<Adr> l=new ArrayList<>(); try(Connection c=c(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT id,title,status,date,context,decision,consequences_json,related_specs_json,source_path FROM adrs")){while(r.next()){ Path p=Path.of(r.getString(9)); if(Files.exists(p)){ var d=yaml.read(p); if(d.adr!=null){ l.add(d.adr); continue; } } l.add(new Adr(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),Json.stringList(r.getString(7)),impacts("adr",r.getString(1)),Json.stringList(r.getString(8)),r.getString(9)));}}catch(Exception e){throw new IllegalStateException(e);} return l;}
 Optional<Adr> adr(String id){return adrs().stream().filter(a->a.id().equals(id)).findFirst();}
 List<Guideline> guidelines(){List<Guideline> l=new ArrayList<>(); try(Connection c=c(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT id,title,languages_json,repository_types_json,rules_json,source_path FROM guidelines")){while(r.next()){ GuidelineRule[] rules=Json.read(r.getString(5), GuidelineRule[].class); l.add(new Guideline(r.getString(1),r.getString(2),new AppliesTo(Json.stringList(r.getString(3)),Json.stringList(r.getString(4))),List.of(rules),r.getString(6)));}}catch(Exception e){throw new IllegalStateException(e);} return l;}
 private List<String> impacts(String type,String id)throws SQLException{String sql="spec".equals(type)?"SELECT repository_id FROM spec_repository_impact WHERE spec_id=?":"SELECT repository_id FROM adr_repository_impact WHERE adr_id=?"; List<String> l=new ArrayList<>(); try(Connection c=c(); PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,id);try(ResultSet r=ps.executeQuery()){while(r.next())l.add(r.getString(1));}} return l;}
}
